accelerator: gpu
activation: silu
attn_activation: silu
batch_size: 4
cutoff: 5.0
dataset: MD17
dataset_arg: aspirin
dataset_root: ./molecule_data/aspirin_data
derivative: true
distributed_backend: ddp
early_stopping_patience: 600
embedding_dimension: 256
energy_weight: 0.05
force_weight: 0.95
inference_batch_size: 16
lmax: 2
load_model: null
log_dir: aspirin_log_1
loss_scale_dy: 1.0
loss_scale_y: 0.05
loss_type: MSE
lr: 0.0004
lr_factor: 0.8
lr_min: 1.0e-07
lr_patience: 30
lr_warmup_steps: 1000
max_num_neighbors: 32
max_z: 100
model: ViSNetBlock
ngpus: -1
num_epochs: 1000
num_heads: 8
num_layers: 9
num_nodes: 1
num_rbf: 32
num_workers: 12
out_dir: run_4
output_model: Scalar
precision: 32
prior_args: null
prior_model: null
rbf_type: expnorm
redirect: false
reduce_op: add
reload: 0
save_interval: 1
seed: 1
split_mode: null
splits: null
standardize: true
task: train
test_interval: 1500
test_size: null
train_size: 950
trainable_rbf: false
trainable_vecnorm: false
use_substructures: true
val_size: 50
vecnorm_type: none
vertex_type: None
weight_decay: 0.0
